In [2]:
import glob
import pandas as pd

In [ ]:
# Use glob to get all the CSVs.
files = glob.glob("../../raw_data/Ottawa_Transit_Data/*.csv")

In [66]:
# Initialize storage file.
data = None
# Loop over individual data files.
for file in files:
    # Use first file to initialize.
    if data is None:
        data = pd.read_csv(file)
        # Create column to join on.
        data['time_stamp'] = [m + ' ' + str(y) for m,y in zip(data['Month'], data["Year"])]
    else:
        temp = pd.read_csv(file)
        # Create column to join on.
        temp['time_stamp'] = [m + ' ' + str(y) for m,y in zip(temp['Month'], temp["Year"])]
        # Remove duplicate columns.
        temp = temp.drop(columns=['Month', 'Year'])
        # Join data frames.
        data = data.join(temp.set_index('time_stamp'), on='time_stamp')
# Drop now redundant join column.
data = data.drop(columns=['time_stamp'])
data.head(5)

,Year,Month,Overall Service Reliability,Service Reliability - On-Time Performance - Para Transpo,Average Time To Answer,Service Reliability - On-Time Performance - Bus,Para Transpo Ridership,Ridership - Conventional,Service Availability - Train and Bus,Call Handled,Service Reliability - Excess Wait Time - Bus,Service Reliability - Excess Wait Time - O-Train Line 1
0,2019,January,97.63%,85.00%,29.47,NaN,75306,"8,910,000",97.63%,"45,557",NaN,NaN
1,2019,February,96.64%,83.20%,35.05,NaN,69038,"8,360,000",96.64%,"41,334",NaN,NaN
2,2019,March,98.23%,91.10%,47.75,NaN,80277,"8,900,000",98.23%,"39,535",NaN,NaN
3,2019,April,97.69%,91.30%,47.45,NaN,76946,"8,390,000",97.69%,"37,836",NaN,NaN
4,2019,May,95.62%,89.70%,47.75,NaN,79713,"7,240,000",95.62%,"37,471",NaN,NaN

In [ ]:
# Save combined result.
data.to_csv('../../raw_data/Ottawa_Transit_Data/ottawa_all.csv', sep=',')